import { axiosClient } from "./axiosClient";

export const adminApi = {
  dashboard: () => axiosClient.get("/admin/dashboard"),
  users: (params) => axiosClient.get("/admin/users", { params }),
  updateUser: (id, payload) => axiosClient.patch(`/admin/users/${id}`, payload),
  tours: (params) => axiosClient.get("/admin/tours", { params }),
  createTour: (payload) => axiosClient.post("/admin/tours", payload),
  updateTour: (id, payload) => axiosClient.patch(`/admin/tours/${id}`, payload),
  deleteTour: (id) => axiosClient.delete(`/admin/tours/${id}`),
  promotions: (params) => axiosClient.get("/admin/promotions", { params }),
  createPromotion: (payload) => axiosClient.post("/admin/promotions", payload),
  updatePromotion: (id, payload) => axiosClient.patch(`/admin/promotions/${id}`, payload),
  deletePromotion: (id) => axiosClient.delete(`/admin/promotions/${id}`),
  uploadImage: (formData) => axiosClient.post("/admin/uploads/images", formData, {
    headers: { "Content-Type": "multipart/form-data" },
  }),
  createTourImage: (tourId, payload) => axiosClient.post(`/admin/tours/${tourId}/images`, payload),
  updateTourImage: (id, payload) => axiosClient.patch(`/admin/tour-images/${id}`, payload),
  deleteTourImage: (id) => axiosClient.delete(`/admin/tour-images/${id}`),
  createTourItinerary: (tourId, payload) => axiosClient.post(`/admin/tours/${tourId}/itineraries`, payload),
  updateTourItinerary: (id, payload) => axiosClient.patch(`/admin/tour-itineraries/${id}`, payload),
  deleteTourItinerary: (id) => axiosClient.delete(`/admin/tour-itineraries/${id}`),
  createTourDeparture: (tourId, payload) => axiosClient.post(`/admin/tours/${tourId}/departures`, payload),
  deleteTourDeparture: (id) => axiosClient.delete(`/admin/tour-departures/${id}`),
  bookings: (params) => axiosClient.get("/admin/bookings", { params }),
  confirmBooking: (id) => axiosClient.patch(`/admin/bookings/${id}/confirm`),
  cancelBooking: (id) => axiosClient.patch(`/admin/bookings/${id}/cancel`),
  completeBooking: (id) => axiosClient.patch(`/admin/bookings/${id}/complete`),
  rejectRefund: (id, note) => axiosClient.patch(`/admin/bookings/${id}/reject-refund`, null, { params: { note } }),
  createPayment: (payload) => axiosClient.post("/admin/payments", payload),
  markPaymentPaid: (id) => axiosClient.patch(`/admin/payments/${id}/mark-paid`),
  markPaymentFailed: (id) => axiosClient.patch(`/admin/payments/${id}/mark-failed`),
  refundPayment: (id) => axiosClient.patch(`/admin/payments/${id}/refund`),
  reviews: (params) => axiosClient.get("/admin/reviews", { params }),
  updateReview: (id, payload) => axiosClient.patch(`/admin/reviews/${id}`, payload),
  deleteReview: (id) => axiosClient.delete(`/admin/reviews/${id}`),
  chatSessions: (params) => axiosClient.get("/admin/chat-sessions", { params }),
  chatMessages: (sessionId, params) => axiosClient.get(`/admin/chat-sessions/${sessionId}/messages`, { params }),
  contacts: () => axiosClient.get("/contacts"),
  replyContact: (id, payload) => axiosClient.patch(`/contacts/${id}/reply`, payload),
  knowledge: (params) => axiosClient.get("/knowledge", { params }),
  uploadKnowledge: (formData) => axiosClient.post("/knowledge/upload", formData, {
    headers: { "Content-Type": "multipart/form-data" },
  }),
  deleteKnowledge: (id) => axiosClient.delete(`/knowledge/${id}`),
};
